import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { cookies } from 'next/headers';
import StoreInitializer from '@/components/layout/StoreInitializer';

export default function RootLayout({ children }) {

  const locale =  'fr';

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const stored = localStorage.getItem('theme-storage');
                  if (stored) {
                    const { state } = JSON.parse(stored);
                    const theme = state.theme || 'acid';
                    const darkThemes = ['synthwave', 'halloween', 'forest', 'black', 'luxury', 'dracula', 'night', 'coffee', 'business'];
                    const isDark = darkThemes.includes(theme);
                    
                    document.documentElement.setAttribute('data-theme', theme);
                    document.documentElement.className = isDark ? 'dark' : 'light';
                  }
                } catch (e) {
                  // Fallback to default theme
                  document.documentElement.setAttribute('data-theme', 'acid');
                  document.documentElement.className = 'light';
                }
              })();
            `,
          }}
        />
      </head>
      <body className="w-full min-w-0 overflow-x-hidden">
          <NextIntlClientProvider>
            <StoreInitializer>
              <div className="w-full min-w-0 overflow-x-hidden">
                {children}
              </div>
            </StoreInitializer>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}

// Metadata
export const metadata = {
  title: 'Artware',
  description: 'Generated by create next app',
};