import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { cookies } from 'next/headers';
import StoreInitializer from '@/components/layout/StoreInitializer';

export default function RootLayout({ children }) {

  const locale =  'fr';

  return (
    <html lang={locale} suppressHydrationWarning>
      
      <body>
          <NextIntlClientProvider>
            <StoreInitializer>
              {children}
            </StoreInitializer>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}

// Metadata
export const metadata = {
  title: 'Artware',
  description: 'Generated by create next app',
};